targets:
    $default:
        builders:
            mobx_codegen|mobx_generator:
                enabled: true
                generate_for:
                    - lib/**/*.store.dart 
                    - lib/**/*.controller.dart 
            chopper_generator:
                enabled: true
                generate_for:
                    - lib/**/*.service.dart 
            json_serializable:
                enabled: true
                generate_for:
                    - lib/**/*.dto.dart 
                    - lib/**/*.model.dart 
