name: appserap
description: SERAp Estudantes.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.2+152

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  percent_indicator: ^3.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  intl: ^0.17.0
  flutter_native_splash: ^1.2.3
  package_info_plus: ^1.3.0

  # Conexão
  cross_connectivity: ^3.0.3
  # connectivity_plus: ^1.1.0
  retry: ^3.1.0

  # Render html
  flutter_html: ^2.1.2

  # Firebase
  firebase_messaging: ^10.0.7
  firebase_core: ^1.6.0
  firebase_messaging_web: ^2.0.5
  firebase_core_web: ^1.1.0

  # Http api
  chopper: ^4.0.5

  # Injecao de dependencias
  get_it: ^7.2.0

  # Banco de dados local
  shared_preferences: ^2.0.7

  # Logger
  logger: ^1.1.0

  # mobx
  mobx: ^2.0.0
  flutter_mobx: ^2.0.0

  # vizualizar imagem
  photo_view: ^0.12.0
  flutter_svg: ^0.22.0
  lottie: ^1.1.0

  # Editor de texto
  html_editor_enhanced: ^2.3.0

  # Workmanager
  # background   _fetch: ^1.0.1
  workmanager: ^0.5.0-dev.7

  # criptografia da senha da prova
  crypto: ^3.0.1
  
  # adaptacao de tela
  flutter_screenutil: ^5.0.0+2

  #database
  drift: ^1.0.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  supercharged: ^2.1.1
  idb_shim: ^2.0.1

  # Informações do dispoisitivo
  device_info_plus: ^3.1.1

  # Navegação
  go_router: ^2.5.7
  url_launcher: 6.0.18

  # Reprodução
  flutter_sound: ^8.5.0

  # Video player
  chewie: ^1.2.2

dependency_overrides:
  flutter_colorpicker: ^0.6.0
  provider: 6.0.1
  url_launcher_web: 2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  build_runner: ^2.1.2
  chopper_generator: ^4.0.1
  mobx_codegen: ^2.0.0
  drift_dev: ^1.0.2
  json_annotation: ^4.1.0
  json_serializable: ^5.0.0

scripts:
  clean: flutter clean flutter pub get
  mobx: flutter pub run build_runner build
  mobx-dco: flutter pub run build_runner build --delete-conflicting-outputs
  mobx-w: flutter pub run build_runner watch --delete-conflicting-outputs
  mobx-c: flutter pub run build_runner clean
  release: flutter build apk --release
  release-web: flutter build web --release
  build-web: flutter build web --profile

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo-serap.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - config/app_config.json
    - fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: fonts/Poppins-Thin.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300          
        - asset: fonts/Poppins-Medium.ttf          
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf          
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Black.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 900   
          
    - family: OpenDyslexic
      fonts:
        - asset: fonts/OpenDyslexic-Regular.ttf 
        - asset: fonts/OpenDyslexic-Bold.ttf
          weight: 700
        

