name: appserap
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  percent_indicator: ^3.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  intl: ^0.17.0
  google_fonts: ^2.1.0
  flutter_native_splash: ^1.2.3
  asuka: ^2.0.0-nullsafety.3

  # Conexão
  cross_connectivity: ^3.0.3
  # connectivity_plus: ^1.1.0

  # Render html
  flutter_html: ^2.1.2

  # Firebase
  firebase_messaging: ^10.0.7
  firebase_core: ^1.6.0
  firebase_messaging_web: ^2.0.5
  firebase_core_web: ^1.1.0

  # Http api
  chopper: ^4.0.1

  # Injecao de dependencias
  get_it: ^7.2.0

  # Banco de dados local
  shared_preferences: ^2.0.7

  # Logger
  logger: ^1.1.0

  # mobx
  mobx: ^2.0.0
  flutter_mobx: ^2.0.0

  # vizualizar imagem
  photo_view: ^0.12.0
  flutter_svg: ^0.22.0
  lottie: ^1.1.0

  # Editor de texto
  html_editor_enhanced: ^2.3.0

  # Workmanager
  # background   _fetch: ^1.0.1
  workmanager: ^0.5.0-dev.7

  #criptografia da senha da prova
  crypto: ^3.0.1

dependency_overrides:
  flutter_colorpicker: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  build_runner: ^2.1.2
  chopper_generator: ^4.0.1
  json_annotation: ^4.1.0
  json_serializable: ^4.1.4
  mobx_codegen: ^2.0.0

scripts:
  clean: flutter clean flutter pub get
  mobx: flutter pub run build_runner build
  mobx-dco: flutter pub run build_runner build --delete-conflicting-outputs
  mobx-w: flutter pub run build_runner watch --delete-conflicting-outputs
  mobx-c: flutter pub run build_runner clean
  release: flutter build apk --release
  release-web: flutter build web --release
  build-web: flutter build web --profile

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo-serap.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - google_fonts/
    - config/app_config.json
    - fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


fonts:
  - family: Poppins
    fonts:
      - asset: google_fonts/Poppins-ExtraLight.ttf
        weight: 100
      - asset: google_fonts/Poppins-Thin.ttf
        weight: 200
      - asset: google_fonts/Poppins-Light.ttf
        weight: 300          
      - asset: google_fonts/Poppins-Regular.ttf          
        weight: 400
      - asset: google_fonts/Poppins-Medium.ttf          
        weight: 500
      - asset: google_fonts/Poppins-SemiBold.ttf          
        weight: 600
      - asset: google_fonts/Poppins-Bold.ttf
        weight: 700
      - asset: google_fonts/Poppins-Black.ttf
        weight: 800
      - asset: google_fonts/Poppins-ExtraBold.ttf
        weight: 900   
        
  - family: OpenDyslexic
    fonts:
      - asset: fonts/OpenDyslexic-Regular.ttf 
        

