
name: CI-CD
 
on:

  push:
    branches: [ development, release, release-r2, master]
    paths-ignore:
    - ".github/workflows/**"  
  
  workflow_dispatch:

jobs:

  flutter_conf_dev:
    runs-on: master
    if: ${{ github.ref == 'refs/heads/development' }}
    environment:
      name: development
    steps:
      - uses: actions/checkout@v3
      - name: Ajustando configuração
        env: # Ou como uma variável de ambiente
          APP_CONFIG: ${{ secrets.APP_CONFIG }}
        run: |
          mkdir -p config && echo $APP_CONFIG > config/app_config.json
          env
         
  flutter_conf_rel:
    runs-on: master
    if: ${{ github.ref == 'refs/heads/release' }}
    environment:
      name: release
    steps:
      - uses: actions/checkout@v3
      - name: Ajustando configuração
        env: # Ou como uma variável de ambiente
          APP_CONFIG: ${{ secrets.APP_CONFIG }}
        run: |
          mkdir -p config && echo $APP_CONFIG > config/app_config.json
          
  flutter_conf_rel2:
    runs-on: master
    if: ${{ github.ref == 'refs/heads/release-r2' }}
    environment:
      name: release
    steps:
      - uses: actions/checkout@v3
      - name: Ajustando configuração
        env: # Ou como uma variável de ambiente
          APP_CONFIG: ${{ secrets.APP_CONFIG_HOM2 }}
        run: |
          mkdir -p config && echo $APP_CONFIG > config/app_config.json
          
  flutter_conf_master:
     runs-on: master
     if: ${{ github.ref == 'refs/heads/master' }}
     environment:
       name: master
     steps:
       - uses: actions/checkout@v3
       - name: Ajustando configuração
         env: # Ou como uma variável de ambiente
           APP_CONFIG: ${{ secrets.APP_CONFIG }}
         run: |
           mkdir -p config && echo $APP_CONFIG > config/app_config.json

  build_dev:
    runs-on: master
    if: ${{ github.ref == 'refs/heads/development' }}
    environment:
      name: development
    needs: [flutter_conf_dev]
    steps:
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
          
      - name: Build the Docker image
        run: |
               docker login ${{ secrets.REGISTRY_HOST }}
               docker build -f Dockerfile.flutter --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-front .
               docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-front
  
  build_release:
    runs-on: master
    if: ${{ github.ref == 'refs/heads/release' }}
    environment:
      name: release
    needs: [flutter_conf_rel]
    steps:
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
          
      - name: Build the Docker image
        run: |
               docker login ${{ secrets.REGISTRY_HOST }}
               docker build -f Dockerfile.flutter --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-front .
               docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-front
               
  build_release-r2:
    runs-on: master
    if: ${{ github.ref == 'refs/heads/release-r2' }}
    environment:
      name: release
    needs: [flutter_conf_rel2]
    steps:
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
          
      - name: Build the Docker image
        run: |
               docker login ${{ secrets.REGISTRY_HOST }}
               docker build -f Dockerfile.flutter --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-front .
               docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-front
 
  build_master:
     runs-on: master
     if: ${{ github.ref == 'refs/heads/master' }}
     environment:
       name: master
     needs: [flutter_conf_master]
     steps:
       - name: Login to registry
         uses: docker/login-action@v2
         with:
           registry: ${{ secrets.REGISTRY_HOST }}
           username: ${{ secrets.REGISTRY_USER }}
           password: ${{ secrets.REGISTRY_PWD }}

       - name: Build the Docker image
         run: |
                docker login ${{ secrets.REGISTRY_HOST }}
                docker build -f Dockerfile.flutter --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-front .
                docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-front

  deploy-development:
    runs-on: master
    if: ${{ github.ref == 'refs/heads/development' }}
    environment:
      name: development
    needs: [ build_dev ]
    steps:
      - name: Redeploy
        uses: prefeiturasp/SME-GithubAction-Images/@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: sme-prova-serap-front
          NAMESPACE: sme-serap-estudante
 
         
  deploy-release:
    runs-on: master
    if: ${{ github.ref == 'refs/heads/release' }}
    environment:
      name: release
    needs: [ build_release ]
    steps:
      - name: Redeploy
        uses: prefeiturasp/SME-GithubAction-Images/@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: sme-prova-serap-front
          NAMESPACE: sme-serap-estudante
          
  deploy-release2:
    runs-on: master
    if: ${{ github.ref == 'refs/heads/release-r2' }}
    environment:
      name: release
    needs: [ build_release-r2 ]
    steps:
      - name: Redeploy
        uses: prefeiturasp/SME-GithubAction-Images/@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: sme-prova-serap-front
          NAMESPACE: sme-serap-estudante
          
  deploy-master:
    runs-on: master
    if: ${{ github.ref == 'refs/heads/master' }}
    environment:
      name: master
    needs: [ build_master ]
    steps:
      - name: Redeploy
        uses: prefeiturasp/SME-GithubAction-Images/@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: sme-prova-serap-front
          NAMESPACE: sme-serap-estudante
