
name: Docker Image CI
 
on:

  push:
    branches: [ development, release, master]
    paths-ignore:
    - ".github/workflows/**"  
  
  workflow_dispatch:

jobs:

  ajuste_env:
    runs-on: master
    steps:
      - name: Ajuste de variaveis para ambiente de desenvolvimento
        if: ${{ github.ref == 'refs/heads/development' }}
        run: echo "::set-env name=ENVIRONMENT::development"
        
      - name: Ajuste de variaveis para ambiente de homologacao
        if: ${{ github.ref == 'refs/heads/release' }}
        run: echo "::set-env name=ENVIRONMENT::release"  
        
      - name: Ajuste de variaveis para ambiente de produção
        if: ${{ github.ref == 'refs/heads/master' }}
        run: echo "::set-env name=ENVIRONMENT::master" 

  flutter_conf:
    runs-on: master
    needs: ajuste_env
    steps:      
      - uses: actions/checkout@v2
      - name: Ajustando configuração
        env: # Ou como uma variável de ambiente
          APP_CONFIG: ${{ secrets.APP_CONFIG }}
        run: |
          mkdir -p config && echo $APP_CONFIG > config/app_config.json

  build:
    runs-on: master
    needs: [flutter_conf]
    steps:
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
          
      - name: Build the Docker image
        run: |
               docker build -f Dockerfile.flutter --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-front .
               docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-front  
             
  deploy:
    runs-on: master
    needs: [ build ]
    steps:
      - name: Redeploy
        uses: luizhpriotto/action_images@kubectl-v1.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: sme-prova-serap-front
          NAMESPACE: sme-serap-estudante
